"""
Auto Block Request Document Generator
AI-Powered Automatic Block Planning System - Indian Railways (SIH Project)

Problem this solves:
Even after the AI decides the optimal joint block schedule, railway
officers still have to manually write up a formal block request
(as submitted through BDMS) - including justification, duration, and
departments involved. This script closes that last-mile gap by
auto-generating a ready-to-submit block request document for every
planned block, pulling directly from the defect and priority data
already computed by prioritize.py and optimize.py.

Hours-saved logic:
In the siloed (current/manual) process, each department that has work
on this section would request its OWN full block window separately.
So the "before" cost is (number of departments involved) x (this
block's duration) - not the sum of individual task durations, since
a department cannot get less than one full block for its work.
The "after" cost is just this single joint block's duration, since
all departments share it.

Output: a formatted text file per block plan, saved in
./generated_requests/, plus a combined summary file.
"""

import os
from datetime import datetime
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

print("Connected to Supabase.\n")

# -----------------------------
# STEP 1: Fetch block plan and defect data
# -----------------------------
plan_resp = supabase.table("block_plan_output").select("*").order("planned_date").execute()
block_plans = plan_resp.data

defects_resp = supabase.table("defects").select("*").execute()
defects_by_id = {d["defect_id"]: d for d in defects_resp.data}

print(f"{len(block_plans)} block plan entries found.\n")


def urgency_label(defect_list):
    """
    Determines the overall urgency label for a block based on the
    most severe defect included in it.
    """
    if any(d["safety_signal"] for d in defect_list):
        return "URGENT (Safety-critical)"
    max_severity = max((d["severity"] or 0) for d in defect_list)
    if max_severity >= 7:
        return "HIGH"
    elif max_severity >= 4:
        return "MEDIUM"
    return "LOW"


def build_justification(defect_list):
    """
    Builds a human-readable justification block, one line per defect,
    mirroring how an officer would write it manually.
    """
    lines = []
    for d in defect_list:
        safety_note = ", Safety-critical" if d["safety_signal"] else ""
        lines.append(
            f"- {d['defect_id']} ({d['department']}): {d['defect_type']} "
            f"— Severity {d['severity']}/10, {d['days_overdue']} days overdue{safety_note}"
        )
    return "\n".join(lines)


def generate_document(block, defect_list):
    """
    Formats a single block request document as plain text,
    matching the structure of a real BDMS block request submission.
    """
    departments = block["departments_included"]
    urgency = urgency_label(defect_list)

    joint_hours = block["duration_hours"]
    num_departments = len(set(d["department"] for d in defect_list))

    # Siloed baseline: each department involved would need its own
    # full block of the same duration if requesting separately.
    siloed_estimate_hours = num_departments * joint_hours
    hours_saved = max(siloed_estimate_hours - joint_hours, 0)

    doc = f"""
BLOCK REQUEST FORM
{'=' * 50}
Section        : {block['section_id']}
Date           : {block['planned_date']}
Time Window    : {block['start_time']} ({block['duration_hours']} hours)
Departments    : {departments}
Plan Horizon   : {block['plan_horizon'].capitalize()}

Justification:
{build_justification(defect_list)}

Priority Level        : {urgency}
Combined Block Hours   : {joint_hours} hours
Estimated Separate Hours (if each department requested individually): {siloed_estimate_hours} hours
Hours Saved via Joint Scheduling: {hours_saved} hours

Generated by: RailBlock AI - Automatic Block Planning System
Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}
Status: Pending Section Controller Approval
{'=' * 50}
"""
    return doc


# -----------------------------
# STEP 2: Generate a document for each block plan entry
# -----------------------------
os.makedirs("generated_requests", exist_ok=True)

all_documents = []

for idx, block in enumerate(block_plans, start=1):
    defect_ids = [x.strip() for x in block["defect_ids"].split(",")] if block.get("defect_ids") else []
    defect_list = [defects_by_id[did] for did in defect_ids if did in defects_by_id]

    if not defect_list:
        continue

    document_text = generate_document(block, defect_list)
    all_documents.append(document_text)

    filename = f"generated_requests/block_request_{block['plan_horizon']}_{idx:03d}.txt"
    with open(filename, "w") as f:
        f.write(document_text)

# Combined file with all requests together (useful for a single demo file)
with open("generated_requests/all_block_requests_combined.txt", "w") as f:
    f.write("\n\n".join(all_documents))

print(f"Generated {len(all_documents)} block request documents.")
print("Saved in ./generated_requests/")
print("Combined file: ./generated_requests/all_block_requests_combined.txt")